In [3]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\daniel.borba\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\daniel.borba\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.5 MB 3.9 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.5 MB 3.5 MB/s eta 0:00:03
   --------- ------------------------------ 2.6/11.5 MB 4.0 MB/s eta 0:00:03
   ----------- ---------------------------- 3.4/11.5 MB 4.1 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.5 MB 4.6 MB/s eta 0:00:02
   --------------------- ------------------ 6.0/11.5 MB 4.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.1/11.5 MB 4.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 5.1 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 5.3 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 5.2 MB/s eta 0:00:00
Downloading numpy-2.2.3-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 7.1 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.6 MB 6.5 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.6 MB 6.0 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 5.9 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 5.8 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 5.9 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 6.1 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.2 MB/s eta 0:00:00
Downloading pytz-2025.1-py2.py3-none-any.whl (507 kB)
Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.3 pandas-2.2.3 pytz-2025.1 tzdata-2025.1

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
df = pd.read_excel('./nextplay.xlsx', sheet_name = 'vendas')
pd.set_option('display.width', 1000)
print(df.head())

   venda_id  cliente_id data_venda  valor_total
0         1           8 2025-01-01      3800.00
1         2          10 2025-01-03      3500.00
2         3          24 2025-01-03       199.98
3         4          32 2025-01-04       199.98
4         5          57 2025-01-05       202.50

In [6]:
df = df.set_index('venda_id')

In [7]:
df['valor_total'].dtype

dtype('float64')

## Lucro total

In [8]:
lucro_total = df['valor_total'].sum()
print(f'O lucro bruto da empresa foi de R$ {lucro_total}')

O lucro bruto da empresa foi de R$ 208822.99

## Quantidade de vendas realizadas

In [9]:
total_vendas = len(df)
print(f'A empresa fez um total de {total_vendas} vendas')

A empresa fez um total de 99 vendas

## Ticket médio

In [10]:
ticket_medio = lucro_total / total_vendas
print(f'O valor do ticket médio é R$ {ticket_medio.round(2)}')

O valor do ticket médio é R$ 2109.32

In [11]:
df_itens = pd.read_excel('nextplay.xlsx', sheet_name='itens_vendas')
df_itens

     item_id  venda_id  produto_id  quantidade  preco_unitario
0          1         1           2           1         3800.00
1          2         2           3           1         3500.00
2          3         3          23           2           99.99
3          4         4          24           2           99.99
4          5         5          14           1          202.50
..       ...       ...         ...         ...             ...
247      248        95          41           1           81.00
248      249        96          39           1           94.50
249      250        97          39           1           94.50
250      251        98          39           1           94.50
251      252        99          39           1           94.50

[252 rows x 5 columns]

In [12]:
df_produtos = pd.read_excel('nextplay.xlsx', sheet_name='produtos')
df_produtos.head()

   produto_id                     nome                                descricao   preco  qtd_estoque  categoria_id
0           1                 Notebook               Notebook de última geração  3500.0            0             1
1           2            Notebook Asus                          Asus Machine v2  3800.0            0             1
2           3  Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050  4320.0            0             1
3           4          PS5 Versão slim                 Sony ps5 videogame 120hz  3510.0            0             2
4           5            XBOX Series X                     Microsoft videogame   4320.0            0             2

In [13]:
## Unindo as tabela
vendas = pd.merge(df, df_itens, on='venda_id', how='left')
print(vendas)

     venda_id  cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario
0           1           8 2025-01-01      3800.00        1           2           1         3800.00
1           2          10 2025-01-03      3500.00        2           3           1         3500.00
2           3          24 2025-01-03       199.98        3          23           2           99.99
3           4          32 2025-01-04       199.98        4          24           2           99.99
4           5          57 2025-01-05       202.50        5          14           1          202.50
..        ...         ...        ...          ...      ...         ...         ...             ...
247        95          51 2025-03-25       175.50      248          41           1           81.00
248        96           1 2025-03-26        94.50      249          39           1           94.50
249        97          18 2025-03-27        94.50      250          39           1           94.50
250        98          83 2025-03-28        94.50      251          39           1           94.50
251        99          26 2025-03-29        94.50      252          39           1           94.50

[252 rows x 8 columns]

In [14]:
relatorio_de_vendas = pd.merge(vendas, df_produtos, on='produto_id', how='left')
print(relatorio_de_vendas.head())

   venda_id  cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                     nome                                descricao    preco  qtd_estoque  categoria_id
0         1           8 2025-01-01      3800.00        1           2           1         3800.00            Notebook Asus                          Asus Machine v2  3800.00          0.0           1.0
1         2          10 2025-01-03      3500.00        2           3           1         3500.00  Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050  4320.00          0.0           1.0
2         3          24 2025-01-03       199.98        3          23           2           99.99     Gift card PSN R$ 100          Gift card playstation 100 reais    99.99          0.0          11.0
3         4          32 2025-01-04       199.98        4          24           2           99.99    Gift card XBOX R$ 100                 Gift card Xbox 100 reais    99.99          0.0          11.0
4         5          57 2025-01-05       202.50        5          14           1          202.50   Mouse red dragon cobra            Mouse preto red dragon cobra    202.50          0.0          13.0

In [15]:
relatorio_de_vendas = relatorio_de_vendas.drop(columns=['qtd_estoque'])
relatorio_de_vendas

     venda_id  cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                         nome                                descricao    preco  categoria_id
0           1           8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2  3800.00           1.0
1           2          10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050  4320.00           1.0
2           3          24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais    99.99          11.0
3           4          32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais    99.99          11.0
4           5          57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra    202.50          13.0
..        ...         ...        ...          ...      ...         ...         ...             ...                          ...                                      ...      ...           ...
247        95          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led    81.00           7.0
248        96           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50           7.0
249        97          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50           7.0
250        98          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50           7.0
251        99          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50           7.0

[252 rows x 12 columns]

In [16]:
relatorio_de_vendas['categoria_id'] = relatorio_de_vendas['categoria_id'].fillna(0).astype(int)

In [17]:
relatorio_de_vendas = relatorio_de_vendas.set_index('venda_id')

In [18]:
df_categorias = pd.read_excel('nextplay.xlsx', sheet_name='categorias')

In [19]:
df_categorias

    categoria_id                      nome
0              1                 Notebooks
1              2                  Consoles
2              3                  Pc Gamer
3              4                 Jogos ps4
4              5                 Jogos ps5
5              6  Jogos de Nintendo Switch
6              7                Acessórios
7              8               Jogos Retro
8              9            Cadeiras Gamer
9             10             Colecionáveis
10            11    Assinaturas e Serviços
11            12               Simuladores
12            13               Periféricos

In [20]:
relatorio_de_vendas = pd.merge(relatorio_de_vendas, df_categorias, on='categoria_id', how='left')
relatorio_de_vendas

     cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                       nome_x                                descricao    preco  categoria_id                  nome_y
0             8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2  3800.00             1               Notebooks
1            10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050  4320.00             1               Notebooks
2            24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais    99.99            11  Assinaturas e Serviços
3            32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais    99.99            11  Assinaturas e Serviços
4            57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra    202.50            13             Periféricos
..          ...        ...          ...      ...         ...         ...             ...                          ...                                      ...      ...           ...                     ...
247          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led    81.00             7              Acessórios
248           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50             7              Acessórios
249          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50             7              Acessórios
250          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50             7              Acessórios
251          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte    94.50             7              Acessórios

[252 rows x 12 columns]

In [21]:
relatorio_de_vendas = relatorio_de_vendas.drop(columns=(['preco']))

In [22]:
relatorio_de_vendas = relatorio_de_vendas.drop(columns=(['categoria_id']))

In [23]:
relatorio_de_vendas

     cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                       nome_x                                descricao                  nome_y
0             8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2               Notebooks
1            10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050               Notebooks
2            24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais  Assinaturas e Serviços
3            32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais  Assinaturas e Serviços
4            57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra              Periféricos
..          ...        ...          ...      ...         ...         ...             ...                          ...                                      ...                     ...
247          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led              Acessórios
248           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
249          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
250          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
251          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios

[252 rows x 10 columns]

In [24]:

relatorio_de_vendas.rename(columns={'nome_x': 'produtos'})

     cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                     produtos                                descricao                  nome_y
0             8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2               Notebooks
1            10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050               Notebooks
2            24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais  Assinaturas e Serviços
3            32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais  Assinaturas e Serviços
4            57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra              Periféricos
..          ...        ...          ...      ...         ...         ...             ...                          ...                                      ...                     ...
247          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led              Acessórios
248           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
249          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
250          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
251          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios

[252 rows x 10 columns]

In [25]:
relatorio_de_vendas = relatorio_de_vendas.rename(columns={'nome_y': 'categoria', 'nome_x': 'nome'})

In [26]:
vendas_por_categoria = relatorio_de_vendas.groupby('categoria')['preco_unitario'].sum().reset_index()

In [27]:
vendas_por_categoria = vendas_por_categoria.sort_values(['preco_unitario'])

In [ ]:
# vendas_por_categoria.to_csv('vendas_por_categoria.csv',index=False)

In [28]:
relatorio_de_vendas

     cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                         nome                                descricao               categoria
0             8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2               Notebooks
1            10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050               Notebooks
2            24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais  Assinaturas e Serviços
3            32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais  Assinaturas e Serviços
4            57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra              Periféricos
..          ...        ...          ...      ...         ...         ...             ...                          ...                                      ...                     ...
247          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led              Acessórios
248           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
249          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
250          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios
251          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios

[252 rows x 10 columns]

In [31]:
relatorio_de_vendas['mes'] = relatorio_de_vendas['data_venda'].dt.month_name(locale='pt_BR')
relatorio_de_vendas

     cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                         nome                                descricao               categoria      mes
0             8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2               Notebooks  Janeiro
1            10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050               Notebooks  Janeiro
2            24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais  Assinaturas e Serviços  Janeiro
3            32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais  Assinaturas e Serviços  Janeiro
4            57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra              Periféricos  Janeiro
..          ...        ...          ...      ...         ...         ...             ...                          ...                                      ...                     ...      ...
247          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led              Acessórios    Março
248           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
249          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
250          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
251          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março

[252 rows x 11 columns]

In [32]:
vendas_por_mes = relatorio_de_vendas.groupby('mes')['preco_unitario'].sum().reset_index()
vendas_por_mes

         mes  preco_unitario
0  Fevereiro       106763.01
1    Janeiro        31627.97
2      Março        70232.13

In [ ]:
vendas_por_categoria.to_csv('vendas_por_categoria.csv', index=False)

                   categoria  preco_unitario
1     Assinaturas e Serviços         1399.86
4   Jogos de Nintendo Switch         3294.00
0                 Acessórios         4893.75
5                  Jogos ps4         5615.95
6                  Jogos ps5         5792.95
2             Cadeiras Gamer         6142.50
10               Simuladores        11340.00
9                Periféricos        13810.60
8                   Pc Gamer        24367.50
7                  Notebooks        63980.00
3                   Consoles        67905.00

In [33]:
vendas_por_mes.to_csv('vendas_por_mês.csv', index=False)

In [34]:
relatorio_de_vendas

     cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                         nome                                descricao               categoria      mes
0             8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2               Notebooks  Janeiro
1            10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050               Notebooks  Janeiro
2            24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais  Assinaturas e Serviços  Janeiro
3            32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais  Assinaturas e Serviços  Janeiro
4            57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra              Periféricos  Janeiro
..          ...        ...          ...      ...         ...         ...             ...                          ...                                      ...                     ...      ...
247          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led              Acessórios    Março
248           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
249          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
250          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
251          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março

[252 rows x 11 columns]

In [36]:
produtos_mais_vendidos = relatorio_de_vendas.groupby('produto_id').agg({'nome': 'first', 'preco_unitario':'sum'}).reset_index()
produtos_mais_vendidos

    produto_id                                       nome  preco_unitario
0            1                                   Notebook        28000.00
1            2                              Notebook Asus        15200.00
2            3                    Notebook Acer Nitro V15        20780.00
3            4                            PS5 Versão slim        10530.00
4            5                              XBOX Series X        17280.00
5            6                              XBOX Series S        12150.00
6            7                PC gamer Zeus Ryzen 7 5700g        11812.50
7            8              PC gamer Mirage i9 + 32gb ram        12555.00
8            9                            Nitendo Switch         10125.00
9           10                         Cadeira Gamer TGT          2835.00
10          11                   Cadeira gamer Superframe         3307.50
11          12                     Mouse attack shark x11         1795.60
12          13               Teclado machenike switch red         2079.00
13          14                     Mouse red dragon cobra         1215.00
14          15                 Mouse red dragon cobra PRO         1350.00
15          16                     Mouse razer Deathadder         1012.50
16          17           Teclado Red dragon daksa rainbow         1215.00
17          18                  Headset Redragon Zeus Pro         1687.50
18          19                    Headset Astro A10 Gen 2         2362.50
19          20               Headset Redragon Hylas Preto         1093.50
20          21                              Logitech G923        11340.00
21          22                            PS4 Versão slim        17820.00
22          23                       Gift card PSN R$ 100          299.97
23          24                      Gift card XBOX R$ 100         1099.89
24          25                PS4: Resident Evil 4 Remake         1228.50
25          26                            PS4: Elden Ring         1248.75
26          27                             PS4: Minecraft          810.00
27          28          PS4: The last of us Remasterizado          911.25
28          29  PS4: Uncharted the nathan drake collecion          742.50
29          30                             PS4: Fallout 4          674.95
30          31                 PS5: Marvel's Spider-Man 2         1249.95
31          32                            PS5: Elden Ring          864.00
32          33                     PS5: Final Fantasy XVI          876.00
33          34                   PS5: God of War Ragnarok         1053.00
34          35                          PS5: Sports FC 25         1750.00
35          36         Switch: Super mario Party Jamboree         1282.50
36          37                Switch: Super mario Odyssey         1255.50
37          38         Switch: Mario & Luigi: Brothership          756.00
38          39                Prisma suporte para headset         1039.50
39          40                        Medusa Mouse pad GG         1188.00
40          41                    Mouse pad Pro G com LED         1053.00
41          42          Suporte controle ps4 e ps5 Gengar          756.00
42          43                   Suporte controle PS5 PRO          486.00
43          44              Suporte para controle de XBOX          371.25
44          81                                       None           81.00

In [39]:
produtos_mais_vendidos = produtos_mais_vendidos.rename(columns={'preco_unitario': 'total_vendas'})
produtos_mais_vendidos.set_index('produto_id')

                                                 nome  total_vendas
produto_id
1                                            Notebook      28000.00
2                                       Notebook Asus      15200.00
3                             Notebook Acer Nitro V15      20780.00
4                                     PS5 Versão slim      10530.00
5                                       XBOX Series X      17280.00
6                                       XBOX Series S      12150.00
7                         PC gamer Zeus Ryzen 7 5700g      11812.50
8                       PC gamer Mirage i9 + 32gb ram      12555.00
9                                     Nitendo Switch       10125.00
10                                 Cadeira Gamer TGT        2835.00
11                           Cadeira gamer Superframe       3307.50
12                             Mouse attack shark x11       1795.60
13                       Teclado machenike switch red       2079.00
14                             Mouse red dragon cobra       1215.00
15                         Mouse red dragon cobra PRO       1350.00
16                             Mouse razer Deathadder       1012.50
17                   Teclado Red dragon daksa rainbow       1215.00
18                          Headset Redragon Zeus Pro       1687.50
19                            Headset Astro A10 Gen 2       2362.50
20                       Headset Redragon Hylas Preto       1093.50
21                                      Logitech G923      11340.00
22                                    PS4 Versão slim      17820.00
23                               Gift card PSN R$ 100        299.97
24                              Gift card XBOX R$ 100       1099.89
25                        PS4: Resident Evil 4 Remake       1228.50
26                                    PS4: Elden Ring       1248.75
27                                     PS4: Minecraft        810.00
28                  PS4: The last of us Remasterizado        911.25
29          PS4: Uncharted the nathan drake collecion        742.50
30                                     PS4: Fallout 4        674.95
31                         PS5: Marvel's Spider-Man 2       1249.95
32                                    PS5: Elden Ring        864.00
33                             PS5: Final Fantasy XVI        876.00
34                           PS5: God of War Ragnarok       1053.00
35                                  PS5: Sports FC 25       1750.00
36                 Switch: Super mario Party Jamboree       1282.50
37                        Switch: Super mario Odyssey       1255.50
38                 Switch: Mario & Luigi: Brothership        756.00
39                        Prisma suporte para headset       1039.50
40                                Medusa Mouse pad GG       1188.00
41                            Mouse pad Pro G com LED       1053.00
42                  Suporte controle ps4 e ps5 Gengar        756.00
43                           Suporte controle PS5 PRO        486.00
44                      Suporte para controle de XBOX        371.25
81                                               None         81.00

In [42]:
relatorio_de_vendas

     cliente_id data_venda  valor_total  item_id  produto_id  quantidade  preco_unitario                         nome                                descricao               categoria      mes
0             8 2025-01-01      3800.00        1           2           1         3800.00                Notebook Asus                          Asus Machine v2               Notebooks  Janeiro
1            10 2025-01-03      3500.00        2           3           1         3500.00      Notebook Acer Nitro V15  Notebook gamer i5 + 8 gb ram + RTX 3050               Notebooks  Janeiro
2            24 2025-01-03       199.98        3          23           2           99.99         Gift card PSN R$ 100          Gift card playstation 100 reais  Assinaturas e Serviços  Janeiro
3            32 2025-01-04       199.98        4          24           2           99.99        Gift card XBOX R$ 100                 Gift card Xbox 100 reais  Assinaturas e Serviços  Janeiro
4            57 2025-01-05       202.50        5          14           1          202.50       Mouse red dragon cobra            Mouse preto red dragon cobra              Periféricos  Janeiro
..          ...        ...          ...      ...         ...         ...             ...                          ...                                      ...                     ...      ...
247          51 2025-03-25       175.50      248          41           1           81.00      Mouse pad Pro G com LED                 Mouse pad grande com led              Acessórios    Março
248           1 2025-03-26        94.50      249          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
249          18 2025-03-27        94.50      250          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
250          83 2025-03-28        94.50      251          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março
251          26 2025-03-29        94.50      252          39           1           94.50  Prisma suporte para headset                     Acessório de Suporte              Acessórios    Março

[252 rows x 11 columns]

In [43]:
produtos_mais_vendidos.to_csv('top_produtos.csv', index=False)